# Generated by Django 4.2.6 on 2023-10-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("dob", models.DateField()),
                ("age", models.IntegerField(max_length=10)),
                ("gender", models.CharField(max_length=2, null=True)),
                ("phonenumber", models.CharField(max_length=250)),
                ("mailid", models.EmailField(max_length=150)),
                ("address", models.CharField(max_length=250, null=True)),
                ("department", models.CharField(max_length=250)),
                ("course", models.CharField(max_length=250)),
                ("material", models.BooleanField(default=True)),
            ],
        ),
    ]
