# Generated by Django 4.2.6 on 2023-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="age",
            field=models.CharField(max_length=250),
        ),
    ]
