# Generated by Django 4.2.6 on 2023-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0002_alter_form_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="dob",
            field=models.IntegerField(),
        ),
    ]
