# Generated by Django 4.2.6 on 2023-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schoolapp", "0003_alter_form_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="dob",
            field=models.TextField(),
        ),
    ]
